### PR TITLE
Skip crc checks to fix performance issues

### PR DESCRIPTION
**Pull request by LGriffioen**

### CODE REVIEW

**Comment by LGriffioen** [comment]
see if they will accept these changes into the main repo

**Comment by pianogamer5** [comment]
Found their [CONTRIBUTING.md](https://github.com/weichsel/ZIPFoundation/blob/3645f447058119385f767b8cf1e4fe682059363e/.github/CONTRIBUTING.md)

**Comment by LGriffioen** [comment]
my PR got rejected https://github.com/weichsel/ZIPFoundation/pull/215

i can make release builds with and without the crc check and see if performance is ok in release mode, then we can decide if we need the fork or not

**Comment by LGriffioen** [comment]
release testing showed that the checksum doesn't really take extra time. so the only thing we'll need to decide is whether we want to keep these changes for debug mode, otherwise saving really large images will take minutes which could be really annoying for us

**Pull request closed without merging**
